### ISSUE TITLE
Howto - which files should you place Where ?

### ISSUE THREAD

**Issue by stachrom** [html5cat/bootstrap-material-design#1]
Hi html5cat

You write in in your description to place the javascript at the end:

".. Just include the theme right after the Bootstrap CSS and include the javascript at the end of your document"

After "meteor add html5cat:bootstrap-material-design"  

Do I have to include any extra CSS or Javascript on my Client-side code? 

Regards roman

**Comment by html5cat** [comment]
@stachrom sorry for the confusion. Updated the readme. Basically just add the package and styles should be applied.
