### ISSUE TITLE
Files missing?

### ISSUE THREAD

**Issue by sergical** [html5cat/bootstrap-material-design#4]
error: File not found: bootstrap-material-design/dist/css/material.css
error: File not found: bootstrap-material-design/dist/css/material-wfont.css
error: File not found: bootstrap-material-design/dist/js/material.js
error: File not found: bootstrap-material-design/dist/fonts/Material-Design.svg
error: File not found: bootstrap-material-design/dist/fonts/Material-Design.woff
error: File not found: bootstrap-material-design/dist/fonts/Material-Design.eot
error: File not found: bootstrap-material-design/dist/fonts/Material-Design.ttf

Or if they are names differently now, update the references.

**Comment by Amdingo** [comment]
From what I've seen he's excluded the base files in the git....why, I couldn't tell you.

Working on piecing them back together in a fork but spare time is far between right now.

**Comment by html5cat** [comment]
Should be fixed now. Please report it not. Thanks!

**Comment by stachrom** [comment]
Why did you comment the ripples out? 

https://github.com/html5cat/bootstrap-material-design/blob/master/package.js

**Comment by html5cat** [comment]
They were causing some issues in previous version. Do they work nicely now?

Best regards,
Yuriy Dybskiy

**Comment by stachrom** [comment]
Hi Yuriy

I'm not aware of major  issues cosed by ripples.js.  

https://github.com/FezVrasta/bootstrap-material-design/issues?q=is%3Aissue+is%3Aopen+ripples

Regards roman

**Comment by html5cat** [comment]
I think it was with some of the plugins I was playing with locally.
Also, according to authors:

```
RipplesJS

This is part of Material Design for Bootstrap project and is a plain Javascript script which creates the ripple effect on click of the defined elements. At the moment RipplesJS does not have its own repository but it will probably have one in the future.
```
