### ISSUE TITLE
Ripple.js commented out?

### ISSUE THREAD

**Issue by jwaltz** [html5cat/bootstrap-material-design#5]
In package.js the ripple.js files are commented out. Is there a reason for this? I found the commit (b5ad05ec2625aece92bbd5a8fa7fe7fe1d947339) when these files were commented out but the commit message doesn't quite explain why.

**Comment by mbabauer** [comment]
Is this what is causing the following error for me:
   Uncaught ReferenceError: ripples is not defined

**Comment by benstr** [comment]
Bummer, I wonder why? @html5cat

**Comment by r00tuzr** [comment]
after i add bootstrap-mat-design i call   $.material.init(); to use the ripple effects on buttons and to give all material effects.
but i get a error in console. "Uncaught ReferenceError: ripples is not defined"
floating labels dont float and buttons dont ripple

error happens here
 "ripples": function(selector) {                                                         // 109
            ripples.init((selector) ? selector : this.options.withRipples);                     // 110
        },

**Comment by html5cat** [comment]
Folks, latest version of original theme might work. I'll update soon

**Comment by r00tuzr** [comment]
Thankx html5cat

**Comment by dandv** [comment]
Hey guys,

@html5cat asked me to help with integrating this theme with Meteor, so I've submitted [a PR](https://github.com/FezVrasta/bootstrap-material-design/pull/291) directly to @fezvrasta's repo that will enable him to publish updates as he releases them. Also, ripples and everything else works (there is a [full test suite](https://github.com/FezVrasta/bootstrap-material-design/pull/291/files#diff-6)).

You can already use the package [from Atmosphere](https://atmospherejs.com/fezvrasta/bootstrap-material-design):

```
meteor add fezvrasta:bootstrap-material-design
```

Thanks again to Yuri for making this theme available for Meteor and so popular!

**Comment by northcoders-chris** [comment]
Awesome thanks!!

**Comment by northcoders-chris** [comment]
Unfortunately, still no ripples.

**Comment by northcoders-chris** [comment]
Do they need to be initialised in the template rendered?

**Comment by northcoders-chris** [comment]
https://github.com/chrishill627/no-ripples

**Comment by northcoders-chris** [comment]
Cool, I got a couple of things working in the template rendered functions, I think they could be initialised in your master layout template rendered, I plan to make a Meteor app and get all the elements working and I will write an extensive README and comment template rendered function, It may be of use to make it very clear to people how to get the package up and running in a Meteor app!

**Comment by MichaelFlops** [comment]
yes please!

**Comment by dandv** [comment]
Look ma, no initialization necessary - https://github.com/FezVrasta/bootstrap-material-design/commit/4b1001f80493d25336d89d7a2bebd446d5c8ef41

PS: please file new issues at https://github.com/FezVrasta/ and CC @dandv :)
